#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build

RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y libpng-dev libjpeg-dev curl libxi6 build-essential libgl1-mesa-glx
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs

ENV LAUNCH_DEV_NODE_SERVER=f
ENV	ASPNETCORE_ENVIRONMENT=Development
EXPOSE 8083
EXPOSE 44360
WORKDIR /src
COPY ["SpotifyDiscovery/SpotifyDiscovery.csproj", "SpotifyDiscovery/"]
RUN dotnet restore "SpotifyDiscovery/SpotifyDiscovery.csproj"
COPY . .
WORKDIR "/src/SpotifyDiscovery"
RUN dotnet dev-certs https &&\
	dotnet dev-certs https -ep /usr/local/share/ca-certificates/aspnet/https.crt --format PEM &&\
	update-ca-certificates

WORKDIR /app
COPY /SpotifyDiscovery /app
RUN dotnet build "SpotifyDiscovery.csproj" -c Release -o /app/build
ENTRYPOINT ["dotnet", "run"]